set -g @catppuccin_directory_color          "#94e2d5"
set -g @catppuccin_window_current_color      "#45475a"
set -g @catppuccin_window_current_background "#1e1e2e"
set -g @catppuccin_window_default_color      "#9399b2"
set -g @catppuccin_window_default_background "#1e1e2e"
set -g @catppuccin_pane_active_border_style  "fg=#94e2d5"
set -g @catppuccin_pane_border_style         "fg=#6c7086"
set -g @catppuccin_status_background         "default"
set -g @catppuccin_session_color             "#{?client_prefix,#89b4fa,#a6e3a1}"
set -g @catppuccin_window_default_fill       "number"
set -g @catppuccin_window_default_text       "#[fg=#cdd6f4]#W"
set -g @catppuccin_window_current_fill       "number"
set -g @catppuccin_window_current_text       "#W#{?window_zoomed_flag,#[fg=#89b4fa] (zoom),}#{?pane_synchronized,#[fg=#89b4fa] SYNC,}"
set -wgF mode-style                          "fg=#a6e3a1,bg=#f2cdcd"
