format = """
$username$hostname$time$all$directory
$character
"""

[character]
success_symbol = '[❯❯❯❯](#a6e3a1 bold)'
error_symbol   = '[✗✗✗✗](#f38ba8 bold)'
vicmd_symbol   = '[❮❮❮❮](#89b4fa bold)'

[battery]
disabled = true

[time]
disabled = false
style    = '#89b4fa bold'
format   = '[\[\]]($style) '
time_format = '%y/%m/%d'

[username]
show_always = true
style_user  = '#89b4fa bold'
style_root  = 'white bold'
format      = '[$user]($style).@.'

[hostname]
ssh_only = true
format   = '(white bold)[$hostname](#a6e3a1 bold)'

[directory]
style             = '#94e2d5 bold'
truncation_length = 0
truncate_to_repo  = false

[ruby]
detect_variables = []
detect_files     = ['Gemfile', '.ruby-version']
